feature/anton_apr1
terzerm/hover-raft pull request #2
Opened 2016-11-19 13:13 UTC by anton-anufriev

Added Log, LogEntry, CommandLogEntry
Change CommandMessage. Added AppendRequestHandler for all states and overrode logic for Candidate state.
De-inherited DirectCommand from Message.
Added replayEvent flag to Transition.

2016-11-19 22:01 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/event/AppendRequestHandler.java
> +    private final VolatileState volatileState;
you don't need those member variables cause they are passed to the onAppendRequest method via ServerContext

2016-11-20 09:38 UTC, terzerm requested changes
Must fixes in my opinion:
- exposure of AbstractDirectMessage
- CommandMessageLog implementing LogEntry --- it should be _has a_ instead of _is a_ relation

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/event/AppendRequestHandler.java
> +        CommandLog.CONTAINMENT containment =  commandLog.contains(prevLogEntry);
final

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/message/MessageType.java
> +        public AbstractDirectMessage create(final DirectMessageFactory factory) {
I don't like if abstract types are exposed anywhere

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/message/direct/DirectAppendRequest.java
> +        directCommandLogEntry.wrap(buffer, offset + COMMAND_LOG_ENTRY_OFF);
nice!

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/message/direct/DirectAppendRequest.java
> +        directCommandLogEntry.unwrap();
should be opposite unwrapping order imo

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/message/direct/DirectMessageFactory.java
> +            final AbstractDirectMessage message = messageType.create(this);
don't like that abstractXXXmessage is exposed

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/CandidateState.java
> +            return super.onAppendRequest(serverContext, appendRequest);
not sure I like that

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/CommandLog.java
> +public interface CommandLog extends LogEntry, Comparable<LogEntry> {
it is dodgy that CommandLog _is a_ LogEntry

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +        throw new IllegalArgumentException("Read index " + readIndex + " has reached end of message log with size " + commandLogEntries.size());
there are no arguments. this is either IllegalStateEx or it should never be possible to get into this situation.

It should actually only occur if index=0 and log is empty. I would throw an IllegalStateException in this case

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +        commandLogEntries.add(Objects.requireNonNull(commandLogEntry));
maybe we should clone here somehow

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +    public synchronized void truncate(long index) {
method name could be clearer, e.g. ``truncateIncluding(..)``

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +
minor: extra empty lines

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +    public int compareTo(LogEntry logEntry) {
I think CommandLog should have a method
``LogEntry lastEntry()``

and not implement LogEntry and also not be comparable to LogEntry.

LogEntry itself then implements Comparable<LogEntry>

Note that ``index()`` should then probably become ``lastIndex()`` or be removed

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/Transition.java
> +    public final boolean replayEvent() {
nice. I like this change.

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/direct/DirectCommandLogEntry.java
> +public class DirectCommandLogEntry implements CommandLogEntry, DirectMessage {
nice. I like this class.

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/state/direct/DirectPersistentState.java
> +        return null;
throwing an exception is better

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/transport/aeron/AeronReceiver.java
> +public class AeronReceiver implements Receiver<AbstractDirectMessage> {
no way --- i really don't like that AbstractDirectMessage is now exposed everywhere.

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/transport/chronicle/ChronicleMessageLog.java
> +        return 0;
throw ex

2016-11-20 09:38 UTC, terzerm commented on src/main/java/org/tools4j/hoverraft/transport/embedded/InMemoryMessageLog.java
> +        return 0;
throw ex

2016-11-20 09:38 UTC, terzerm commented on src/test/java/org/tools4j/hoverraft/server/FollowerStateTest.java
> +        when(persistentState.commandLog().contains(appendRequest.prevLogEntry())).thenReturn(CommandLog.CONTAINMENT.IN);
extract commandLog and prefLogEntry into variable for readability

2016-11-20 09:38 UTC, terzerm commented on src/test/java/org/tools4j/hoverraft/server/VoteRequestHandlerTest.java
> +                .index(lastLogIndex);
that's the disadvantage of the nested object structure --- the method chaining breaks down :-(

2016-11-20 09:38 UTC, terzerm commented on src/test/java/org/tools4j/hoverraft/server/VoteRequestHandlerTest.java
> +        when(persistentState.commandLog().compareTo(voteRequest.lastLogEntry())).thenReturn(1);
extract commandLog and lastLogEntry into variable for readability

2016-11-20 09:38 UTC, terzerm commented on src/test/java/org/tools4j/hoverraft/state/InMemoryCommandLogTest.java
> +    }
poor test coverage

2016-11-20 14:05 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/message/MessageType.java
> +        public AbstractDirectMessage create(final DirectMessageFactory factory) {
Yeah, I did think about that and left it for discussion. Fixed now.

2016-11-20 14:07 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/message/direct/DirectAppendRequest.java
> +        directCommandLogEntry.unwrap();
fixed

2016-11-20 14:07 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/message/direct/DirectMessageFactory.java
> +            final AbstractDirectMessage message = messageType.create(this);
fixed

2016-11-20 14:08 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/CommandLog.java
> +public interface CommandLog extends LogEntry, Comparable<LogEntry> {
Agree, fixed.

2016-11-20 14:11 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +        throw new IllegalArgumentException("Read index " + readIndex + " has reached end of message log with size " + commandLogEntries.size());
Copied from your InMemoryMessageLog. Agree that IllegalStateEx is better.

2016-11-20 14:12 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +        throw new IllegalArgumentException("Read index " + readIndex + " has reached end of message log with size " + commandLogEntries.size());
Fixed in both

2016-11-20 14:14 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +        commandLogEntries.add(Objects.requireNonNull(commandLogEntry));
I think it is better that InMemoryFactory with InMemoryMessages

2016-11-20 14:15 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +    public synchronized void truncate(long index) {
done

2016-11-20 14:16 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +
easy

2016-11-20 15:19 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/InMemoryCommandLog.java
> +    public int compareTo(LogEntry logEntry) {
Yes, I have done it.

2016-11-20 15:20 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/direct/DirectPersistentState.java
> +        return null;
nice! done

2016-11-20 15:21 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/transport/aeron/AeronReceiver.java
> +public class AeronReceiver implements Receiver<AbstractDirectMessage> {
it was a temporary change. Fixed

2016-11-20 15:28 UTC, anton-anufriev commented on src/test/java/org/tools4j/hoverraft/server/FollowerStateTest.java
> +        when(persistentState.commandLog().contains(appendRequest.prevLogEntry())).thenReturn(CommandLog.CONTAINMENT.IN);
done

2016-11-20 15:32 UTC, anton-anufriev commented on src/test/java/org/tools4j/hoverraft/server/VoteRequestHandlerTest.java
> +        when(persistentState.commandLog().compareTo(voteRequest.lastLogEntry())).thenReturn(1);
done

2016-11-22 14:53 UTC, anton-anufriev commented on src/main/java/org/tools4j/hoverraft/state/CandidateState.java
> +            return super.onAppendRequest(serverContext, appendRequest);
why?

2016-11-23 10:37 UTC, merged